/**
* Meetacy Backend API
* _Version 1.0.2 of the `Meetacy` API documentation_. It is recommended to fill in the request body on your own according to the sample provided below. The `Notifications` section is under development. 
*
* OpenAPI spec version: 1.0.2
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package app.meetacy.sdk.engine.ktor.response.models

import dev.icerock.moko.network.generated.models.Meeting
import kotlinx.serialization.Serializable






import kotlinx.serialization.SerialName


/**
 * 
 * @param result 
 * @param status 
 */
@Serializable
internal data class ListMapMeetingsResponse (
    
    @SerialName("result")
    val result: List<Meeting>,
    
    @SerialName("status")
    val status: Boolean? = null

)

