/**
* Meetacy Backend API
* _Version 1.0.2 of the `Meetacy` API documentation_. It is recommended to fill in the request body on your own according to the sample provided below. The `Notifications` section is under development. 
*
* OpenAPI spec version: 1.0.2
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package app.meetacy.sdk.engine.ktor.response.models

import kotlinx.serialization.Serializable






import kotlinx.serialization.SerialName


/**
 * 
 * @param isSelf 
 * @param id 
 * @param nickname 
 * @param username 
 * @param email 
 * @param emailVerified 
 * @param avatarId 
 * @param relationship Relationship field can be one of four types - subscription, subscriber, friend and none. In case if isSelf == true, relationship field is null
 */
@Serializable
internal data class User (
    
    @SerialName("isSelf")
    val isSelf: Boolean,
    
    @SerialName("id")
    val id: String,
    
    @SerialName("nickname")
    val nickname: String,
    
    @SerialName("username")
    val username: String? = null,
    
    @SerialName("email")
    val email: String? = null,
    
    @SerialName("emailVerified")
    val emailVerified: Boolean? = null,
    
    @SerialName("avatarId")
    val avatarId: String? = null,
    /* Relationship field can be one of four types - subscription, subscriber, friend and none. In case if isSelf == true, relationship field is null */
    
    @SerialName("relationship")
    val relationship: String? = null

)

