name: Library Snapshot Deploy

on:
  push:
    branches-ignore: [ "main" ]
  workflow_dispatch:

jobs:
  snapshot-deploy:
    runs-on: macos-latest
    env:
      GITHUB_USERNAME: "meetacy"
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      ORG_GRADLE_PROJECT_snapshot: true
      ORG_GRADLE_PROJECT_commit: ${{ github.sha }}
      ORG_GRADLE_PROJECT_attempt: ${{ github.run_attempt }}
    steps:
      - uses: actions/checkout@v3
      - name: Gradle Cache Setup
        uses: gradle/gradle-build-action@v2
      - name: Gradle Sync
        run: ./gradlew
      - name: Add Sdk Version to Env
        run: |
          snapshot_version=$(./gradlew printSdkVersion -q)
          echo "snapshot_version=$snapshot_version" >> $GITHUB_ENV
      - name: Publish Jvm Platform ${{ env.snapshot_version }}
        run: ./gradlew publishJvmPublicationToMeetacySdkRepository publishKotlinMultiplatformPublicationToMeetacySdkRepository
      - name: Publish Remaining ${{ env.snapshot_version }}
        run: |
          ./gradlew publishJsPublicationToMeetacySdkRepository publishIosX64PublicationToMeetacySdkRepository \
                    publishIosSimulatorArm64PublicationToMeetacySdkRepository publishIosArm64PublicationToMeetacySdkRepository
