name: Library Release Deploy

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  release-deploy:
    runs-on: macos-latest
    env:
      GITHUB_USERNAME: "meetacy"
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: Gradle Cache Setup
        uses: gradle/gradle-build-action@v2
      - name: Publish Release Libary
        run: ./gradlew publish
      - name: Add Sdk Version to Env
        run: |
          release_version=$(./gradlew printSdkVersion -q)
          echo "release_version=$release_version" >> $GITHUB_ENV
      - name: Create Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ env.release_version }}
          release_name: Release ${{ env.release_version }}
