name: Library Snapshot Deploy

on:
  push:
    branches-ignore: [ "main" ]
  workflow_dispatch:

jobs:
  snapshot-deploy:
    runs-on: macos-latest
    env:
      GITHUB_USERNAME: "meetacy"
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '11'
          cache: 'gradle'
      - name: Gradle Sync
        run: ./gradlew
      - name: Add Sdk Version to Env
        run: |
          snapshot_version=$(./gradlew printSdkVersion -q -Psnapshot=true -Pcommit=${{ github.sha }} -Pattempt=${{ github.run_attempt }})
          echo "snapshot_version=$snapshot_version" >> $GITHUB_ENV
      - name: Publish ${{ env.snapshot_version }}
        run: ./gradlew publish -Psnapshot=true -Pcommit=${{ github.sha }} -Pattempt=${{ github.run_attempt }}
